### ISSUE TITLE
Arduino Firmware for ATTiny841, Spence Konde's ATTinyCore?

### ISSUE THREAD

**Issue by mathewlippincott** [fr293/motor_board#5]
Is this the firmware being used for the ATTiny841?
https://github.com/SpenceKonde/ATTinyCore

**Comment by fr293** [comment]
That’s the one. It seems to be pretty active at the moment, which is good!

Yours truly,

Fergus Riche 
Magdalene College
Cambridge
Mobile: +447974304049

**Comment by mathewlippincott** [comment]
Cool, added info to the readme and made a pull request!
